In [4]:
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix
import skfuzzy

In [3]:
iris=datasets.load_iris()

In [9]:
r=skfuzzy.cmeans(data=iris.data.T,c=3,m=2,error=0.005,maxiter=1000, init=None)

In [10]:
r # Gerou uma tupla

(array([[5.00396392, 3.4141112 , 1.48277731, 0.25352875],
        [6.77410634, 3.05213441, 5.64571891, 2.05317708],
        [5.88842109, 2.76089015, 4.36312659, 1.39686587]]),
 array([[9.96623187e-01, 9.75837330e-01, 9.79815601e-01, 9.67407270e-01,
         9.94469367e-01, 9.34539707e-01, 9.79480949e-01, 9.99546992e-01,
         9.30340915e-01, 9.82711583e-01, 9.68026813e-01, 9.92131589e-01,
         9.70622730e-01, 9.22933689e-01, 8.89717491e-01, 8.41287040e-01,
         9.46902945e-01, 9.96651900e-01, 9.04086982e-01, 9.79179627e-01,
         9.68583424e-01, 9.84825307e-01, 9.58642505e-01, 9.79409772e-01,
         9.66894400e-01, 9.73548436e-01, 9.94840242e-01, 9.93344937e-01,
         9.93673273e-01, 9.79502102e-01, 9.78712302e-01, 9.74348686e-01,
         9.38495281e-01, 9.04133031e-01, 9.85054777e-01, 9.84987025e-01,
         9.64168135e-01, 9.90888431e-01, 9.39652299e-01, 9.98287985e-01,
         9.94726837e-01, 8.50658886e-01, 9.52591267e-01, 9.79273392e-01,
         9.45237067e-

In [11]:
previsoes_porcentagem=r[1]

In [12]:
previsoes_porcentagem[0][0]

0.9966231868540572

In [13]:
previsoes_porcentagem[1][0]

0.0010721376009500978

In [14]:
previsoes_porcentagem[2][0]

0.0023046755449928342

In [15]:
previsoes=previsoes_porcentagem.argmax(axis=0)

In [16]:
previsoes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2])

In [17]:
resultados=confusion_matrix(iris.target,previsoes)

In [18]:
resultados

array([[50,  0,  0],
       [ 0,  3, 47],
       [ 0, 37, 13]])