In [1]:
'''
Uma forma de buscar que os computadores façam tarefas de humanos
Um dos maiores desafios da humanidade - ERROR
Simular as redes neurais biológicas no computador
O que é perceptron? É um tipo de rede neural artificial inventada por 
Frank Rosenblatt. É basicamente o tipo mais simples de rede neural, um classificador
linear.
O que é Deep Learning: É uma área da Machine Learning baseado em um conjunto de
algoritmos que tentam modelar abstrações de alto nível de dados usando um grafo
profundo com várias camadas de processamento, compostas de várias transformações
lineares e não lineares.

Rede Neural Básica utilizando o IRIS

'''


'\nUma forma de buscar que os computadores façam tarefas de humanos\nUm dos maiores desafios da humanidade - ERROR\nSimular as redes neurais biológicas no computador\nO que é perceptron? É um tipo de rede neural artificial inventada por \nFrank Rosenblatt. É basicamente o tipo mais simples de rede neural, um classificador\nlinear.\nO que é Deep Learning: É uma área da Machine Learning baseado em um conjunto de\nalgoritmos que tentam modelar abstrações de alto nível de dados usando um grafo\nprofundo com várias camadas de processamento, compostas de várias transformações\nlineares e não lineares.\n\nRede Neural Básica utilizando o IRIS\n\n'

In [28]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from yellowbrick.classifier import ConfusionMatrix
# Importando Tensorflow (pip install tensorflow)
# Importando Keras (pip install keras)
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np
from sklearn.metrics import confusion_matrix

In [4]:
base = datasets.load_iris()

In [5]:
base

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
previsores = base.data
classe = base.target

In [7]:
previsores

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
classe_dummy = np_utils.to_categorical(classe)

In [11]:
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [19]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores, classe_dummy, test_size = 0.3,random_state=0)

In [20]:
# Construindo a rede neural
modelo = Sequential()

#adicionando as camadas
modelo.add(Dense(units=5,input_dim=4)) # 5 neuronios
modelo.add(Dense(units=4)) # 4 neuronios
modelo.add(Dense(units=3,activation='softmax')) # 3 neuronios

In [21]:
modelo.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_5 (Dense)              (None, 4)                 24        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 15        
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [22]:
from keras.utils.vis_utils import plot_model

In [23]:
modelo.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
modelo.fit(X_treinamento, y_treinamento, epochs=1000, validation_data=(X_teste,y_teste))

Instructions for updating:
Use tf.cast instead.
Train on 105 samples, validate on 45 samples
Epoch 1/1000
105/105 [==============================] - 0s 2ms/step - loss: 6.8659 - accuracy: 0.3048 - val_loss: 4.8889 - val_accuracy: 0.4000
Epoch 2/1000
105/105 [==============================] - 0s 185us/step - loss: 6.7888 - accuracy: 0.3048 - val_loss: 4.8099 - val_accuracy: 0.4000
Epoch 3/1000
105/105 [==============================] - 0s 160us/step - loss: 6.7196 - accuracy: 0.3048 - val_loss: 4.7331 - val_accuracy: 0.4000
Epoch 4/1000
105/105 [==============================] - 0s 161us/step - loss: 6.6502 - accuracy: 0.3048 - val_loss: 4.6602 - val_accuracy: 0.4000
Epoch 5/1000
105/105 [==============================] - 0s 189us/step - loss: 6.5824 - accuracy: 0.3048 - val_loss: 4.5904 - val_accuracy: 0.4000
Epoch 6/1000
105/105 [==============================] - 0s 179us/step - loss: 6.5076 - accuracy: 0.3048 - val_loss: 4.5020 - val_accuracy: 0.4000
Epoch 7/1000
105/105 [===========

105/105 [==============================] - 0s 347us/step - loss: 1.6671 - accuracy: 0.0857 - val_loss: 1.5900 - val_accuracy: 0.1556
Epoch 55/1000
105/105 [==============================] - 0s 258us/step - loss: 1.6502 - accuracy: 0.0952 - val_loss: 1.5667 - val_accuracy: 0.1778
Epoch 56/1000
105/105 [==============================] - 0s 187us/step - loss: 1.6347 - accuracy: 0.0952 - val_loss: 1.5469 - val_accuracy: 0.2000
Epoch 57/1000
105/105 [==============================] - 0s 166us/step - loss: 1.6190 - accuracy: 0.1048 - val_loss: 1.5255 - val_accuracy: 0.2222
Epoch 58/1000
105/105 [==============================] - 0s 174us/step - loss: 1.6056 - accuracy: 0.1048 - val_loss: 1.5102 - val_accuracy: 0.2222
Epoch 59/1000
105/105 [==============================] - 0s 279us/step - loss: 1.5920 - accuracy: 0.1048 - val_loss: 1.4980 - val_accuracy: 0.2222
Epoch 60/1000
105/105 [==============================] - 0s 141us/step - loss: 1.5768 - accuracy: 0.1048 - val_loss: 1.4907 - val_ac

Epoch 110/1000
105/105 [==============================] - 0s 181us/step - loss: 1.1095 - accuracy: 0.2095 - val_loss: 1.1065 - val_accuracy: 0.2000
Epoch 111/1000
105/105 [==============================] - 0s 140us/step - loss: 1.1025 - accuracy: 0.2095 - val_loss: 1.1005 - val_accuracy: 0.2000
Epoch 112/1000
105/105 [==============================] - 0s 172us/step - loss: 1.0950 - accuracy: 0.2095 - val_loss: 1.0974 - val_accuracy: 0.1778
Epoch 113/1000
105/105 [==============================] - 0s 198us/step - loss: 1.0890 - accuracy: 0.2095 - val_loss: 1.0988 - val_accuracy: 0.1556
Epoch 114/1000
105/105 [==============================] - 0s 131us/step - loss: 1.0811 - accuracy: 0.2190 - val_loss: 1.0986 - val_accuracy: 0.1778
Epoch 115/1000
105/105 [==============================] - 0s 136us/step - loss: 1.0746 - accuracy: 0.2571 - val_loss: 1.0941 - val_accuracy: 0.2000
Epoch 116/1000
105/105 [==============================] - 0s 153us/step - loss: 1.0673 - accuracy: 0.2476 - val_

105/105 [==============================] - 0s 158us/step - loss: 0.7235 - accuracy: 0.6762 - val_loss: 0.7553 - val_accuracy: 0.6222
Epoch 166/1000
105/105 [==============================] - 0s 118us/step - loss: 0.7174 - accuracy: 0.6762 - val_loss: 0.7478 - val_accuracy: 0.6222
Epoch 167/1000
105/105 [==============================] - 0s 161us/step - loss: 0.7116 - accuracy: 0.6762 - val_loss: 0.7404 - val_accuracy: 0.6222
Epoch 168/1000
105/105 [==============================] - 0s 156us/step - loss: 0.7051 - accuracy: 0.6762 - val_loss: 0.7279 - val_accuracy: 0.6222
Epoch 169/1000
105/105 [==============================] - 0s 101us/step - loss: 0.6983 - accuracy: 0.6857 - val_loss: 0.7185 - val_accuracy: 0.6222
Epoch 170/1000
105/105 [==============================] - 0s 166us/step - loss: 0.6915 - accuracy: 0.6857 - val_loss: 0.7040 - val_accuracy: 0.6000
Epoch 171/1000
105/105 [==============================] - 0s 169us/step - loss: 0.6863 - accuracy: 0.6857 - val_loss: 0.6902 - 

105/105 [==============================] - 0s 159us/step - loss: 0.5034 - accuracy: 0.7524 - val_loss: 0.5218 - val_accuracy: 0.7111
Epoch 221/1000
105/105 [==============================] - 0s 132us/step - loss: 0.5013 - accuracy: 0.7619 - val_loss: 0.5136 - val_accuracy: 0.7111
Epoch 222/1000
105/105 [==============================] - 0s 141us/step - loss: 0.4982 - accuracy: 0.7810 - val_loss: 0.5111 - val_accuracy: 0.7111
Epoch 223/1000
105/105 [==============================] - 0s 130us/step - loss: 0.4958 - accuracy: 0.7810 - val_loss: 0.5074 - val_accuracy: 0.7111
Epoch 224/1000
105/105 [==============================] - 0s 108us/step - loss: 0.4932 - accuracy: 0.7810 - val_loss: 0.5049 - val_accuracy: 0.7111
Epoch 225/1000
105/105 [==============================] - 0s 123us/step - loss: 0.4909 - accuracy: 0.7810 - val_loss: 0.5024 - val_accuracy: 0.7111
Epoch 226/1000
105/105 [==============================] - 0s 107us/step - loss: 0.4884 - accuracy: 0.7905 - val_loss: 0.4978 - 

105/105 [==============================] - 0s 164us/step - loss: 0.3875 - accuracy: 0.8571 - val_loss: 0.4088 - val_accuracy: 0.8667
Epoch 276/1000
105/105 [==============================] - 0s 144us/step - loss: 0.3868 - accuracy: 0.8476 - val_loss: 0.3987 - val_accuracy: 0.8889
Epoch 277/1000
105/105 [==============================] - 0s 126us/step - loss: 0.3832 - accuracy: 0.8762 - val_loss: 0.3947 - val_accuracy: 0.9111
Epoch 278/1000
105/105 [==============================] - 0s 140us/step - loss: 0.3810 - accuracy: 0.8857 - val_loss: 0.3928 - val_accuracy: 0.9111
Epoch 279/1000
105/105 [==============================] - 0s 137us/step - loss: 0.3792 - accuracy: 0.8857 - val_loss: 0.3923 - val_accuracy: 0.9111
Epoch 280/1000
105/105 [==============================] - 0s 124us/step - loss: 0.3777 - accuracy: 0.8857 - val_loss: 0.3954 - val_accuracy: 0.8889
Epoch 281/1000
105/105 [==============================] - 0s 123us/step - loss: 0.3753 - accuracy: 0.8952 - val_loss: 0.3959 - 

105/105 [==============================] - 0s 159us/step - loss: 0.2926 - accuracy: 0.9524 - val_loss: 0.3117 - val_accuracy: 0.9111
Epoch 331/1000
105/105 [==============================] - 0s 188us/step - loss: 0.2916 - accuracy: 0.9524 - val_loss: 0.3132 - val_accuracy: 0.9111
Epoch 332/1000
105/105 [==============================] - 0s 151us/step - loss: 0.2906 - accuracy: 0.9524 - val_loss: 0.3145 - val_accuracy: 0.9111
Epoch 333/1000
105/105 [==============================] - 0s 245us/step - loss: 0.2899 - accuracy: 0.9333 - val_loss: 0.3136 - val_accuracy: 0.9111
Epoch 334/1000
105/105 [==============================] - 0s 106us/step - loss: 0.2886 - accuracy: 0.9429 - val_loss: 0.3059 - val_accuracy: 0.9111
Epoch 335/1000
105/105 [==============================] - 0s 166us/step - loss: 0.2860 - accuracy: 0.9524 - val_loss: 0.3028 - val_accuracy: 0.9111
Epoch 336/1000
105/105 [==============================] - 0s 123us/step - loss: 0.2840 - accuracy: 0.9524 - val_loss: 0.3035 - 

105/105 [==============================] - 0s 282us/step - loss: 0.2214 - accuracy: 0.9524 - val_loss: 0.2314 - val_accuracy: 0.9333
Epoch 386/1000
105/105 [==============================] - 0s 153us/step - loss: 0.2207 - accuracy: 0.9429 - val_loss: 0.2278 - val_accuracy: 0.9556
Epoch 387/1000
105/105 [==============================] - 0s 219us/step - loss: 0.2191 - accuracy: 0.9524 - val_loss: 0.2273 - val_accuracy: 0.9556
Epoch 388/1000
105/105 [==============================] - 0s 181us/step - loss: 0.2181 - accuracy: 0.9524 - val_loss: 0.2263 - val_accuracy: 0.9556
Epoch 389/1000
105/105 [==============================] - 0s 138us/step - loss: 0.2174 - accuracy: 0.9429 - val_loss: 0.2245 - val_accuracy: 0.9556
Epoch 390/1000
105/105 [==============================] - 0s 177us/step - loss: 0.2157 - accuracy: 0.9524 - val_loss: 0.2175 - val_accuracy: 0.9556
Epoch 391/1000
105/105 [==============================] - 0s 140us/step - loss: 0.2165 - accuracy: 0.9524 - val_loss: 0.2128 - 

105/105 [==============================] - 0s 171us/step - loss: 0.1745 - accuracy: 0.9524 - val_loss: 0.1730 - val_accuracy: 0.9778
Epoch 441/1000
105/105 [==============================] - 0s 268us/step - loss: 0.1740 - accuracy: 0.9524 - val_loss: 0.1726 - val_accuracy: 0.9778
Epoch 442/1000
105/105 [==============================] - 0s 203us/step - loss: 0.1732 - accuracy: 0.9524 - val_loss: 0.1741 - val_accuracy: 0.9778
Epoch 443/1000
105/105 [==============================] - 0s 208us/step - loss: 0.1727 - accuracy: 0.9524 - val_loss: 0.1752 - val_accuracy: 0.9778
Epoch 444/1000
105/105 [==============================] - 0s 203us/step - loss: 0.1712 - accuracy: 0.9524 - val_loss: 0.1758 - val_accuracy: 0.9778
Epoch 445/1000
105/105 [==============================] - 0s 228us/step - loss: 0.1705 - accuracy: 0.9524 - val_loss: 0.1754 - val_accuracy: 0.9778
Epoch 446/1000
105/105 [==============================] - 0s 151us/step - loss: 0.1700 - accuracy: 0.9524 - val_loss: 0.1742 - 

105/105 [==============================] - 0s 203us/step - loss: 0.1437 - accuracy: 0.9524 - val_loss: 0.1431 - val_accuracy: 0.9778
Epoch 496/1000
105/105 [==============================] - 0s 146us/step - loss: 0.1432 - accuracy: 0.9524 - val_loss: 0.1424 - val_accuracy: 0.9778
Epoch 497/1000
105/105 [==============================] - 0s 174us/step - loss: 0.1429 - accuracy: 0.9524 - val_loss: 0.1411 - val_accuracy: 0.9778
Epoch 498/1000
105/105 [==============================] - 0s 138us/step - loss: 0.1428 - accuracy: 0.9619 - val_loss: 0.1410 - val_accuracy: 0.9778
Epoch 499/1000
105/105 [==============================] - 0s 135us/step - loss: 0.1428 - accuracy: 0.9524 - val_loss: 0.1452 - val_accuracy: 0.9778
Epoch 500/1000
105/105 [==============================] - 0s 148us/step - loss: 0.1416 - accuracy: 0.9619 - val_loss: 0.1452 - val_accuracy: 0.9778
Epoch 501/1000
105/105 [==============================] - 0s 148us/step - loss: 0.1416 - accuracy: 0.9619 - val_loss: 0.1421 - 

105/105 [==============================] - 0s 129us/step - loss: 0.1232 - accuracy: 0.9619 - val_loss: 0.1259 - val_accuracy: 0.9778
Epoch 551/1000
105/105 [==============================] - 0s 146us/step - loss: 0.1225 - accuracy: 0.9619 - val_loss: 0.1216 - val_accuracy: 0.9778
Epoch 552/1000
105/105 [==============================] - 0s 160us/step - loss: 0.1225 - accuracy: 0.9619 - val_loss: 0.1190 - val_accuracy: 0.9778
Epoch 553/1000
105/105 [==============================] - 0s 155us/step - loss: 0.1222 - accuracy: 0.9619 - val_loss: 0.1183 - val_accuracy: 0.9778
Epoch 554/1000
105/105 [==============================] - 0s 169us/step - loss: 0.1224 - accuracy: 0.9714 - val_loss: 0.1173 - val_accuracy: 0.9778
Epoch 555/1000
105/105 [==============================] - 0s 182us/step - loss: 0.1223 - accuracy: 0.9714 - val_loss: 0.1180 - val_accuracy: 0.9778
Epoch 556/1000
105/105 [==============================] - 0s 191us/step - loss: 0.1209 - accuracy: 0.9619 - val_loss: 0.1200 - 

105/105 [==============================] - 0s 119us/step - loss: 0.1085 - accuracy: 0.9619 - val_loss: 0.1116 - val_accuracy: 0.9778
Epoch 606/1000
105/105 [==============================] - 0s 159us/step - loss: 0.1084 - accuracy: 0.9619 - val_loss: 0.1119 - val_accuracy: 0.9778
Epoch 607/1000
105/105 [==============================] - 0s 130us/step - loss: 0.1088 - accuracy: 0.9619 - val_loss: 0.1112 - val_accuracy: 0.9778
Epoch 608/1000
105/105 [==============================] - 0s 153us/step - loss: 0.1071 - accuracy: 0.9714 - val_loss: 0.1067 - val_accuracy: 0.9778
Epoch 609/1000
105/105 [==============================] - 0s 129us/step - loss: 0.1103 - accuracy: 0.9714 - val_loss: 0.1029 - val_accuracy: 0.9778
Epoch 610/1000
105/105 [==============================] - 0s 124us/step - loss: 0.1090 - accuracy: 0.9619 - val_loss: 0.1026 - val_accuracy: 0.9556
Epoch 611/1000
105/105 [==============================] - 0s 171us/step - loss: 0.1094 - accuracy: 0.9619 - val_loss: 0.1032 - 

105/105 [==============================] - 0s 184us/step - loss: 0.0975 - accuracy: 0.9810 - val_loss: 0.1009 - val_accuracy: 0.9778
Epoch 661/1000
105/105 [==============================] - 0s 137us/step - loss: 0.0974 - accuracy: 0.9810 - val_loss: 0.0999 - val_accuracy: 0.9778
Epoch 662/1000
105/105 [==============================] - 0s 317us/step - loss: 0.0967 - accuracy: 0.9810 - val_loss: 0.1003 - val_accuracy: 0.9778
Epoch 663/1000
105/105 [==============================] - 0s 196us/step - loss: 0.0968 - accuracy: 0.9810 - val_loss: 0.0996 - val_accuracy: 0.9778
Epoch 664/1000
105/105 [==============================] - 0s 172us/step - loss: 0.0963 - accuracy: 0.9810 - val_loss: 0.0997 - val_accuracy: 0.9778
Epoch 665/1000
105/105 [==============================] - 0s 141us/step - loss: 0.0967 - accuracy: 0.9810 - val_loss: 0.0999 - val_accuracy: 0.9778
Epoch 666/1000
105/105 [==============================] - 0s 196us/step - loss: 0.0962 - accuracy: 0.9810 - val_loss: 0.0981 - 

105/105 [==============================] - 0s 112us/step - loss: 0.0901 - accuracy: 0.9714 - val_loss: 0.0951 - val_accuracy: 0.9778
Epoch 716/1000
105/105 [==============================] - 0s 113us/step - loss: 0.0878 - accuracy: 0.9810 - val_loss: 0.0902 - val_accuracy: 0.9778
Epoch 717/1000
105/105 [==============================] - 0s 99us/step - loss: 0.0890 - accuracy: 0.9619 - val_loss: 0.0873 - val_accuracy: 0.9778
Epoch 718/1000
105/105 [==============================] - 0s 111us/step - loss: 0.0887 - accuracy: 0.9619 - val_loss: 0.0871 - val_accuracy: 0.9778
Epoch 719/1000
105/105 [==============================] - 0s 104us/step - loss: 0.0888 - accuracy: 0.9619 - val_loss: 0.0871 - val_accuracy: 0.9778
Epoch 720/1000
105/105 [==============================] - 0s 112us/step - loss: 0.0884 - accuracy: 0.9619 - val_loss: 0.0879 - val_accuracy: 0.9778
Epoch 721/1000
105/105 [==============================] - 0s 135us/step - loss: 0.0876 - accuracy: 0.9810 - val_loss: 0.0893 - v

105/105 [==============================] - 0s 165us/step - loss: 0.0819 - accuracy: 0.9810 - val_loss: 0.0863 - val_accuracy: 0.9778
Epoch 771/1000
105/105 [==============================] - 0s 235us/step - loss: 0.0805 - accuracy: 0.9810 - val_loss: 0.0840 - val_accuracy: 0.9778
Epoch 772/1000
105/105 [==============================] - 0s 164us/step - loss: 0.0807 - accuracy: 0.9714 - val_loss: 0.0829 - val_accuracy: 0.9778
Epoch 773/1000
105/105 [==============================] - 0s 138us/step - loss: 0.0810 - accuracy: 0.9619 - val_loss: 0.0827 - val_accuracy: 0.9778
Epoch 774/1000
105/105 [==============================] - 0s 146us/step - loss: 0.0808 - accuracy: 0.9619 - val_loss: 0.0832 - val_accuracy: 0.9778
Epoch 775/1000
105/105 [==============================] - 0s 131us/step - loss: 0.0808 - accuracy: 0.9714 - val_loss: 0.0858 - val_accuracy: 0.9778
Epoch 776/1000
105/105 [==============================] - 0s 130us/step - loss: 0.0808 - accuracy: 0.9810 - val_loss: 0.0874 - 

105/105 [==============================] - 0s 147us/step - loss: 0.0756 - accuracy: 0.9810 - val_loss: 0.0813 - val_accuracy: 0.9778
Epoch 826/1000
105/105 [==============================] - 0s 171us/step - loss: 0.0752 - accuracy: 0.9714 - val_loss: 0.0804 - val_accuracy: 0.9778
Epoch 827/1000
105/105 [==============================] - 0s 139us/step - loss: 0.0749 - accuracy: 0.9714 - val_loss: 0.0798 - val_accuracy: 0.9778
Epoch 828/1000
105/105 [==============================] - 0s 139us/step - loss: 0.0744 - accuracy: 0.9714 - val_loss: 0.0788 - val_accuracy: 0.9778
Epoch 829/1000
105/105 [==============================] - 0s 110us/step - loss: 0.0751 - accuracy: 0.9619 - val_loss: 0.0785 - val_accuracy: 0.9778
Epoch 830/1000
105/105 [==============================] - 0s 113us/step - loss: 0.0779 - accuracy: 0.9619 - val_loss: 0.0790 - val_accuracy: 0.9556
Epoch 831/1000
105/105 [==============================] - 0s 127us/step - loss: 0.0813 - accuracy: 0.9619 - val_loss: 0.0794 - 

105/105 [==============================] - 0s 133us/step - loss: 0.0701 - accuracy: 0.9714 - val_loss: 0.0770 - val_accuracy: 0.9778
Epoch 881/1000
105/105 [==============================] - 0s 115us/step - loss: 0.0715 - accuracy: 0.9714 - val_loss: 0.0766 - val_accuracy: 0.9778
Epoch 882/1000
105/105 [==============================] - 0s 112us/step - loss: 0.0700 - accuracy: 0.9714 - val_loss: 0.0775 - val_accuracy: 0.9778
Epoch 883/1000
105/105 [==============================] - 0s 96us/step - loss: 0.0707 - accuracy: 0.9714 - val_loss: 0.0792 - val_accuracy: 0.9778
Epoch 884/1000
105/105 [==============================] - 0s 119us/step - loss: 0.0706 - accuracy: 0.9810 - val_loss: 0.0799 - val_accuracy: 0.9778
Epoch 885/1000
105/105 [==============================] - 0s 118us/step - loss: 0.0702 - accuracy: 0.9714 - val_loss: 0.0773 - val_accuracy: 0.9778
Epoch 886/1000
105/105 [==============================] - 0s 125us/step - loss: 0.0692 - accuracy: 0.9714 - val_loss: 0.0762 - v

105/105 [==============================] - 0s 159us/step - loss: 0.0661 - accuracy: 0.9714 - val_loss: 0.0764 - val_accuracy: 0.9778
Epoch 936/1000
105/105 [==============================] - 0s 153us/step - loss: 0.0651 - accuracy: 0.9810 - val_loss: 0.0786 - val_accuracy: 0.9778
Epoch 937/1000
105/105 [==============================] - 0s 152us/step - loss: 0.0663 - accuracy: 0.9810 - val_loss: 0.0805 - val_accuracy: 0.9778
Epoch 938/1000
105/105 [==============================] - 0s 175us/step - loss: 0.0668 - accuracy: 0.9810 - val_loss: 0.0801 - val_accuracy: 0.9778
Epoch 939/1000
105/105 [==============================] - 0s 165us/step - loss: 0.0664 - accuracy: 0.9810 - val_loss: 0.0785 - val_accuracy: 0.9778
Epoch 940/1000
105/105 [==============================] - 0s 123us/step - loss: 0.0652 - accuracy: 0.9810 - val_loss: 0.0749 - val_accuracy: 0.9778
Epoch 941/1000
105/105 [==============================] - 0s 127us/step - loss: 0.0650 - accuracy: 0.9714 - val_loss: 0.0737 - 

105/105 [==============================] - 0s 245us/step - loss: 0.0631 - accuracy: 0.9714 - val_loss: 0.0736 - val_accuracy: 0.9778
Epoch 991/1000
105/105 [==============================] - 0s 139us/step - loss: 0.0619 - accuracy: 0.9714 - val_loss: 0.0730 - val_accuracy: 0.9778
Epoch 992/1000
105/105 [==============================] - 0s 202us/step - loss: 0.0620 - accuracy: 0.9714 - val_loss: 0.0729 - val_accuracy: 0.9778
Epoch 993/1000
105/105 [==============================] - 0s 199us/step - loss: 0.0621 - accuracy: 0.9714 - val_loss: 0.0731 - val_accuracy: 0.9778
Epoch 994/1000
105/105 [==============================] - 0s 207us/step - loss: 0.0631 - accuracy: 0.9714 - val_loss: 0.0727 - val_accuracy: 0.9778
Epoch 995/1000
105/105 [==============================] - 0s 175us/step - loss: 0.0615 - accuracy: 0.9714 - val_loss: 0.0737 - val_accuracy: 0.9778
Epoch 996/1000
105/105 [==============================] - 0s 170us/step - loss: 0.0617 - accuracy: 0.9714 - val_loss: 0.0751 - 

In [24]:
previsoes=modelo.predict(X_teste)

In [25]:
previsoes

array([[5.2570122e-11, 2.7118539e-04, 9.9972886e-01],
       [4.5139794e-04, 9.9385965e-01, 5.6888885e-03],
       [9.9995375e-01, 4.6275567e-05, 6.0495092e-20],
       [4.9555593e-10, 4.0811994e-03, 9.9591881e-01],
       [9.9930906e-01, 6.9099176e-04, 3.4201277e-16],
       [4.4747725e-12, 9.2497925e-05, 9.9990749e-01],
       [9.9951327e-01, 4.8674931e-04, 1.2796356e-16],
       [8.7661676e-05, 9.8638922e-01, 1.3523091e-02],
       [3.7791604e-05, 9.5625126e-01, 4.3710869e-02],
       [7.1751513e-04, 9.9750924e-01, 1.7732768e-03],
       [2.1566372e-07, 6.0517687e-02, 9.3948203e-01],
       [2.3901351e-04, 9.9468756e-01, 5.0733411e-03],
       [1.9131060e-04, 9.8316491e-01, 1.6643839e-02],
       [4.3213102e-05, 9.3400240e-01, 6.5954357e-02],
       [9.4993404e-05, 9.5209360e-01, 4.7811463e-02],
       [9.9984229e-01, 1.5763995e-04, 7.8889960e-18],
       [1.0055412e-04, 9.4660896e-01, 5.3290542e-02],
       [2.7660202e-04, 9.6305019e-01, 3.6673307e-02],
       [9.9694175e-01, 3.058

In [26]:
previsoes=(previsoes>0.5)

In [27]:
previsoes

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [30]:
#v = ConfusionMatrix()
y_teste_matrix=[np.argmax(t) for t in y_teste]

In [31]:
y_teste_matrix

[2,
 1,
 0,
 2,
 0,
 2,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 1,
 1,
 0,
 2,
 1,
 0,
 2,
 2,
 1,
 0,
 1,
 1,
 1,
 2,
 0,
 2,
 0,
 0]

In [32]:
y_previsao_matrix=[np.argmax(t) for t in previsoes]

In [33]:
y_previsao_matrix

[2,
 1,
 0,
 2,
 0,
 2,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 1,
 1,
 0,
 2,
 1,
 0,
 2,
 2,
 1,
 0,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 0]

In [35]:
confusao=confusion_matrix(y_teste_matrix, y_previsao_matrix)

In [36]:
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])